import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import Header from "../components/Header";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Header />
        <main>
          <article>
            <section
              className="section hero"
              style={{
                backgroundImage: 'url("/assets/images/hero-banner.png")',
              }}
            >
              <div className="container">
                <h2 className="h1 hero-title">
                  New Summer <strong>Shoes Collection</strong>
                </h2>
                <p className="hero-text">
                  Competently expedite alternative benefits whereas leading-edge
                  catalysts for change. Globally leverage existing an expanded
                  array of leadership.
                </p>
                <button className="btn btn-primary">
                  <span>Shop Now</span>
                  {/* <ion-icon name="arrow-forward-outline" aria-hidden="true" /> */}
                </button>
              </div>
            </section>

            <section className="section collection">
              <div className="container">
                <ul className="collection-list has-scrollbar">
                  <li>
                    <div
                      className="collection-card"
                      style={{
                        backgroundImage:
                          'url("/assets/images/collection-1.jpg")',
                      }}
                    >
                      <h3 className="h4 card-title">Men Collections</h3>
                      <a href="#" className="btn btn-secondary">
                        <span>Explore All</span>
                        {/* <ion-icon
                          name="arrow-forward-outline"
                          aria-hidden="true"
                        /> */}
                      </a>
                    </div>
                  </li>
                  <li>
                    <div
                      className="collection-card"
                      style={{
                        backgroundImage:
                          'url("/assets/images/collection-2.jpg")',
                      }}
                    >
                      <h3 className="h4 card-title">Women Collections</h3>
                      <a href="#" className="btn btn-secondary">
                        <span>Explore All</span>
                        {/* <ion-icon
                          name="arrow-forward-outline"
                          aria-hidden="true"
                        /> */}
                      </a>
                    </div>
                  </li>
                  <li>
                    <div
                      className="collection-card"
                      style={{
                        backgroundImage:
                          'url("/assets/images/collection-3.jpg")',
                      }}
                    >
                      <h3 className="h4 card-title">Sports Collections</h3>
                      <a href="#" className="btn btn-secondary">
                        <span>Explore All</span>
                        {/* <ion-icon
                          name="arrow-forward-outline"
                          aria-hidden="true"
                        /> */}
                      </a>
                    </div>
                  </li>
                </ul>
              </div>
            </section>

            <section className="section product">
              <div className="container">
                <h2 className="h2 section-title">Bestsellers Products</h2>
                <ul className="filter-list">
                  <li>
                    <button className="filter-btn  active">All</button>
                  </li>
                  <li>
                    <button className="filter-btn">Nike</button>
                  </li>
                  <li>
                    <button className="filter-btn">Adidas</button>
                  </li>
                  <li>
                    <button className="filter-btn">Puma</button>
                  </li>
                  <li>
                    <button className="filter-btn">Bata</button>
                  </li>
                  <li>
                    <button className="filter-btn">Apex</button>
                  </li>
                </ul>
                <ul className="product-list">
                  <li className="product-item">
                    <div className="product-card" tabIndex={0}>
                      <figure className="card-banner">
                        <Image
                          src="/assets/images/product-1.jpg"
                          width={312}
                          height={350}
                          loading="lazy"
                          alt="Running Sneaker Shoes"
                          className="image-contain"
                        />
                        <div className="card-badge">New</div>
                        <ul className="card-action-list">
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-1"
                            >
                              {/* <ion-icon name="cart-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-1"
                            >
                              Add to Cart
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-2"
                            >
                              {/* <ion-icon name="heart-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-2"
                            >
                              Add to Whishlist
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-3"
                            >
                              {/* <ion-icon name="eye-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-3"
                            >
                              Quick View
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-4"
                            >
                              {/* <ion-icon name="repeat-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-4"
                            >
                              Compare
                            </div>
                          </li>
                        </ul>
                      </figure>
                      <div className="card-content">
                        <div className="card-cat">
                          <a href="#" className="card-cat-link">
                            Men
                          </a>{" "}
                          /
                          <a href="#" className="card-cat-link">
                            Women
                          </a>
                        </div>
                        <h3 className="h3 card-title">
                          <a href="#">Running Sneaker Shoes</a>
                        </h3>
                        <data className="card-price" value="180.85">
                          $180.85
                        </data>
                      </div>
                    </div>
                  </li>
                  <li className="product-item">
                    <div className="product-card" tabIndex={0}>
                      <figure className="card-banner">
                        <Image
                          src="/assets/images/product-2.jpg"
                          width={312}
                          height={350}
                          loading="lazy"
                          alt="Leather Mens Slipper"
                          className="image-contain"
                        />
                        <ul className="card-action-list">
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-1"
                            >
                              {/* <ion-icon name="cart-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-1"
                            >
                              Add to Cart
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-2"
                            >
                              {/* <ion-icon name="heart-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-2"
                            >
                              Add to Whishlist
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-3"
                            >
                              {/* <ion-icon name="eye-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-3"
                            >
                              Quick View
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-4"
                            >
                              {/* <ion-icon name="repeat-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-4"
                            >
                              Compare
                            </div>
                          </li>
                        </ul>
                      </figure>
                      <div className="card-content">
                        <div className="card-cat">
                          <a href="#" className="card-cat-link">
                            Men
                          </a>{" "}
                          /
                          <a href="#" className="card-cat-link">
                            Sports
                          </a>
                        </div>
                        <h3 className="h3 card-title">
                          <a href="#">Leather Mens Slipper</a>
                        </h3>
                        <data className="card-price" value="190.85">
                          $190.85
                        </data>
                      </div>
                    </div>
                  </li>
                  <li className="product-item">
                    <div className="product-card" tabIndex={0}>
                      <figure className="card-banner">
                        <Image
                          src="/assets/images/product-3.jpg"
                          width={312}
                          height={350}
                          loading="lazy"
                          alt="Simple Fabric Shoe"
                          className="image-contain"
                        />
                        <div className="card-badge">New</div>
                        <ul className="card-action-list">
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-1"
                            >
                              {/* <ion-icon name="cart-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-1"
                            >
                              Add to Cart
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-2"
                            >
                              {/* <ion-icon name="heart-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-2"
                            >
                              Add to Whishlist
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-3"
                            >
                              {/* <ion-icon name="eye-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-3"
                            >
                              Quick View
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-4"
                            >
                              {/* <ion-icon name="repeat-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-4"
                            >
                              Compare
                            </div>
                          </li>
                        </ul>
                      </figure>
                      <div className="card-content">
                        <div className="card-cat">
                          <a href="#" className="card-cat-link">
                            Men
                          </a>{" "}
                          /
                          <a href="#" className="card-cat-link">
                            Women
                          </a>
                        </div>
                        <h3 className="h3 card-title">
                          <a href="#">Simple Fabric Shoe</a>
                        </h3>
                        <data className="card-price" value="160.85">
                          $160.85
                        </data>
                      </div>
                    </div>
                  </li>
                  <li className="product-item">
                    <div className="product-card" tabIndex={0}>
                      <figure className="card-banner">
                        <Image
                          src="/assets/images/product-4.jpg"
                          width={312}
                          height={350}
                          loading="lazy"
                          alt="Air Jordan 7 Retro "
                          className="image-contain"
                        />
                        <div className="card-badge"> -25%</div>
                        <ul className="card-action-list">
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-1"
                            >
                              {/* <ion-icon name="cart-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-1"
                            >
                              Add to Cart
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-2"
                            >
                              {/* <ion-icon name="heart-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-2"
                            >
                              Add to Whishlist
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-3"
                            >
                              {/* <ion-icon name="eye-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-3"
                            >
                              Quick View
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-4"
                            >
                              {/* <ion-icon name="repeat-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-4"
                            >
                              Compare
                            </div>
                          </li>
                        </ul>
                      </figure>
                      <div className="card-content">
                        <div className="card-cat">
                          <a href="#" className="card-cat-link">
                            Men
                          </a>{" "}
                          /
                          <a href="#" className="card-cat-link">
                            Sports
                          </a>
                        </div>
                        <h3 className="h3 card-title">
                          <a href="#">Air Jordan 7 Retro </a>
                        </h3>
                        <data className="card-price" value="170.85">
                          $170.85 <del>$200.21</del>
                        </data>
                      </div>
                    </div>
                  </li>
                  <li className="product-item">
                    <div className="product-card" tabIndex={0}>
                      <figure className="card-banner">
                        <Image
                          src="/assets/images/product-5.jpg"
                          width={312}
                          height={350}
                          loading="lazy"
                          alt="Nike Air Max 270 SE"
                          className="image-contain"
                        />
                        <div className="card-badge">New</div>
                        <ul className="card-action-list">
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-1"
                            >
                              {/* <ion-icon name="cart-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-1"
                            >
                              Add to Cart
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-2"
                            >
                              {/* <ion-icon name="heart-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-2"
                            >
                              Add to Whishlist
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-3"
                            >
                              {/* <ion-icon name="eye-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-3"
                            >
                              Quick View
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-4"
                            >
                              {/* <ion-icon name="repeat-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-4"
                            >
                              Compare
                            </div>
                          </li>
                        </ul>
                      </figure>
                      <div className="card-content">
                        <div className="card-cat">
                          <a href="#" className="card-cat-link">
                            Men
                          </a>{" "}
                          /
                          <a href="#" className="card-cat-link">
                            Women
                          </a>
                        </div>
                        <h3 className="h3 card-title">
                          <a href="#">Nike Air Max 270 SE</a>
                        </h3>
                        <data className="card-price" value="120.85">
                          $120.85
                        </data>
                      </div>
                    </div>
                  </li>
                  <li className="product-item">
                    <div className="product-card" tabIndex={0}>
                      <figure className="card-banner">
                        <Image
                          src="/assets/images/product-6.jpg"
                          width={312}
                          height={350}
                          loading="lazy"
                          alt="Adidas Sneakers Shoes"
                          className="image-contain"
                        />
                        <ul className="card-action-list">
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-1"
                            >
                              {/* <ion-icon name="cart-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-1"
                            >
                              Add to Cart
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-2"
                            >
                              {/* <ion-icon name="heart-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-2"
                            >
                              Add to Whishlist
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-3"
                            >
                              {/* <ion-icon name="eye-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-3"
                            >
                              Quick View
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-4"
                            >
                              {/* <ion-icon name="repeat-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-4"
                            >
                              Compare
                            </div>
                          </li>
                        </ul>
                      </figure>
                      <div className="card-content">
                        <div className="card-cat">
                          <a href="#" className="card-cat-link">
                            Men
                          </a>{" "}
                          /
                          <a href="#" className="card-cat-link">
                            Women
                          </a>
                        </div>
                        <h3 className="h3 card-title">
                          <a href="#">Adidas Sneakers Shoes</a>
                        </h3>
                        <data className="card-price" value="100.85">
                          $100.85
                        </data>
                      </div>
                    </div>
                  </li>
                  <li className="product-item">
                    <div className="product-card" tabIndex={0}>
                      <figure className="card-banner">
                        <Image
                          src="/assets/images/product-7.jpg"
                          width={312}
                          height={350}
                          loading="lazy"
                          alt="Nike Basketball shoes"
                          className="image-contain"
                        />
                        <ul className="card-action-list">
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-1"
                            >
                              {/* <ion-icon name="cart-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-1"
                            >
                              Add to Cart
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-2"
                            >
                              {/* <ion-icon name="heart-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-2"
                            >
                              Add to Whishlist
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-3"
                            >
                              {/* <ion-icon name="eye-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-3"
                            >
                              Quick View
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-4"
                            >
                              {/* <ion-icon name="repeat-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-4"
                            >
                              Compare
                            </div>
                          </li>
                        </ul>
                      </figure>
                      <div className="card-content">
                        <div className="card-cat">
                          <a href="#" className="card-cat-link">
                            Men
                          </a>{" "}
                          /
                          <a href="#" className="card-cat-link">
                            Sports
                          </a>
                        </div>
                        <h3 className="h3 card-title">
                          <a href="#">Nike Basketball shoes</a>
                        </h3>
                        <data className="card-price" value="120.85">
                          $120.85
                        </data>
                      </div>
                    </div>
                  </li>
                  <li className="product-item">
                    <div className="product-card" tabIndex={0}>
                      <figure className="card-banner">
                        <Image
                          src="/assets/images/product-8.jpg"
                          width={312}
                          height={350}
                          loading="lazy"
                          alt="Simple Fabric Shoe"
                          className="image-contain"
                        />
                        <ul className="card-action-list">
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-1"
                            >
                              {/* <ion-icon name="cart-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-1"
                            >
                              Add to Cart
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-2"
                            >
                              {/* <ion-icon name="heart-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-2"
                            >
                              Add to Whishlist
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-3"
                            >
                              {/* <ion-icon name="eye-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-3"
                            >
                              Quick View
                            </div>
                          </li>
                          <li className="card-action-item">
                            <button
                              className="card-action-btn"
                              aria-labelledby="card-label-4"
                            >
                              {/* <ion-icon name="repeat-outline" /> */}
                            </button>
                            <div
                              className="card-action-tooltip"
                              id="card-label-4"
                            >
                              Compare
                            </div>
                          </li>
                        </ul>
                      </figure>
                      <div className="card-content">
                        <div className="card-cat">
                          <a href="#" className="card-cat-link">
                            Men
                          </a>{" "}
                          /
                          <a href="#" className="card-cat-link">
                            Women
                          </a>
                        </div>
                        <h3 className="h3 card-title">
                          <a href="#">Simple Fabric Shoe</a>
                        </h3>
                        <data className="card-price" value="100.85">
                          $100.85
                        </data>
                      </div>
                    </div>
                  </li>
                </ul>
              </div>
            </section>

            <section className="section cta">
              <div className="container">
                <ul className="cta-list">
                  <li>
                    <div
                      className="cta-card"
                      style={{
                        backgroundImage: 'url("/assets/images/cta-1.jpg")',
                      }}
                    >
                      <p className="card-subtitle">Adidas Shoes</p>
                      <h3 className="h2 card-title">The Summer Sale Off 50%</h3>
                      <a href="#" className="btn btn-link">
                        <span>Shop Now</span>
                        {/* <ion-icon
                          name="arrow-forward-outline"
                          aria-hidden="true"
                        /> */}
                      </a>
                    </div>
                  </li>
                  <li>
                    <div
                      className="cta-card"
                      style={{
                        backgroundImage: 'url("/assets/images/cta-2.jpg")',
                      }}
                    >
                      <p className="card-subtitle">Nike Shoes</p>
                      <h3 className="h2 card-title">
                        Makes Yourself Keep Sporty
                      </h3>
                      <a href="#" className="btn btn-link">
                        <span>Shop Now</span>
                        {/* <ion-icon
                          name="arrow-forward-outline"
                          aria-hidden="true"
                        /> */}
                      </a>
                    </div>
                  </li>
                </ul>
              </div>
            </section>

            <section className="section special">
              <div className="container">
                <div
                  className="special-banner"
                  style={{
                    backgroundImage: 'url("/assets/images/special-banner.jpg")',
                  }}
                >
                  <h2 className="h3 banner-title">New Trend Edition</h2>
                  <a href="#" className="btn btn-link">
                    <span>Explore All</span>
                    {/* <ion-icon name="arrow-forward-outline" aria-hidden="true" /> */}
                  </a>
                </div>
                <div className="special-product">
                  <h2 className="h2 section-title">
                    <span className="text">Nike Special</span>
                    <span className="line" />
                  </h2>
                  <ul className="has-scrollbar">
                    <li className="product-item">
                      <div className="product-card" tabIndex={0}>
                        <figure className="card-banner">
                          <Image
                            src="/assets/images/product-1.jpg"
                            width={312}
                            height={350}
                            loading="lazy"
                            alt="Running Sneaker Shoes"
                            className="image-contain"
                          />
                          <div className="card-badge">New</div>
                          <ul className="card-action-list">
                            <li className="card-action-item">
                              <button
                                className="card-action-btn"
                                aria-labelledby="card-label-1"
                              >
                                {/* <ion-icon name="cart-outline" /> */}
                              </button>
                              <div
                                className="card-action-tooltip"
                                id="card-label-1"
                              >
                                Add to Cart
                              </div>
                            </li>
                            <li className="card-action-item">
                              <button
                                className="card-action-btn"
                                aria-labelledby="card-label-2"
                              >
                                {/* <ion-icon name="heart-outline" /> */}
                              </button>
                              <div
                                className="card-action-tooltip"
                                id="card-label-2"
                              >
                                Add to Whishlist
                              </div>
                            </li>
                            <li className="card-action-item">
                              <button
                                className="card-action-btn"
                                aria-labelledby="card-label-3"
                              >
                                {/* <ion-icon name="eye-outline" /> */}
                              </button>
                              <div
                                className="card-action-tooltip"
                                id="card-label-3"
                              >
                                Quick View
                              </div>
                            </li>
                            <li className="card-action-item">
                              <button
                                className="card-action-btn"
                                aria-labelledby="card-label-4"
                              >
                                {/* <ion-icon name="repeat-outline" /> */}
                              </button>
                              <div
                                className="card-action-tooltip"
                                id="card-label-4"
                              >
                                Compare
                              </div>
                            </li>
                          </ul>
                        </figure>
                        <div className="card-content">
                          <div className="card-cat">
                            <a href="#" className="card-cat-link">
                              Men
                            </a>{" "}
                            /
                            <a href="#" className="card-cat-link">
                              Women
                            </a>
                          </div>
                          <h3 className="h3 card-title">
                            <a href="#">Running Sneaker Shoes</a>
                          </h3>
                          <data className="card-price" value="180.85">
                            $180.85
                          </data>
                        </div>
                      </div>
                    </li>
                    <li className="product-item">
                      <div className="product-card" tabIndex={0}>
                        <figure className="card-banner">
                          <Image
                            src="/assets/images/product-2.jpg"
                            width={312}
                            height={350}
                            loading="lazy"
                            alt="Leather Mens Slipper"
                            className="image-contain"
                          />
                          <ul className="card-action-list">
                            <li className="card-action-item">
                              <button
                                className="card-action-btn"
                                aria-labelledby="card-label-1"
                              >
                                {/* <ion-icon name="cart-outline" /> */}
                              </button>
                              <div
                                className="card-action-tooltip"
                                id="card-label-1"
                              >
                                Add to Cart
                              </div>
                            </li>
                            <li className="card-action-item">
                              <button
                                className="card-action-btn"
                                aria-labelledby="card-label-2"
                              >
                                {/* <ion-icon name="heart-outline" /> */}
                              </button>
                              <div
                                className="card-action-tooltip"
                                id="card-label-2"
                              >
                                Add to Whishlist
                              </div>
                            </li>
                            <li className="card-action-item">
                              <button
                                className="card-action-btn"
                                aria-labelledby="card-label-3"
                              >
                                {/* <ion-icon name="eye-outline" /> */}
                              </button>
                              <div
                                className="card-action-tooltip"
                                id="card-label-3"
                              >
                                Quick View
                              </div>
                            </li>
                            <li className="card-action-item">
                              <button
                                className="card-action-btn"
                                aria-labelledby="card-label-4"
                              >
                                {/* <ion-icon name="repeat-outline" /> */}
                              </button>
                              <div
                                className="card-action-tooltip"
                                id="card-label-4"
                              >
                                Compare
                              </div>
                            </li>
                          </ul>
                        </figure>
                        <div className="card-content">
                          <div className="card-cat">
                            <a href="#" className="card-cat-link">
                              Men
                            </a>{" "}
                            /
                            <a href="#" className="card-cat-link">
                              Sports
                            </a>
                          </div>
                          <h3 className="h3 card-title">
                            <a href="#">Leather Mens Slipper</a>
                          </h3>
                          <data className="card-price" value="190.85">
                            $190.85
                          </data>
                        </div>
                      </div>
                    </li>
                    <li className="product-item">
                      <div className="product-card" tabIndex={0}>
                        <figure className="card-banner">
                          <Image
                            src="/assets/images/product-3.jpg"
                            width={312}
                            height={350}
                            loading="lazy"
                            alt="Simple Fabric Shoe"
                            className="image-contain"
                          />
                          <div className="card-badge">New</div>
                          <ul className="card-action-list">
                            <li className="card-action-item">
                              <button
                                className="card-action-btn"
                                aria-labelledby="card-label-1"
                              >
                                {/* <ion-icon name="cart-outline" /> */}
                              </button>
                              <div
                                className="card-action-tooltip"
                                id="card-label-1"
                              >
                                Add to Cart
                              </div>
                            </li>
                            <li className="card-action-item">
                              <button
                                className="card-action-btn"
                                aria-labelledby="card-label-2"
                              >
                                {/* <ion-icon name="heart-outline" /> */}
                              </button>
                              <div
                                className="card-action-tooltip"
                                id="card-label-2"
                              >
                                Add to Whishlist
                              </div>
                            </li>
                            <li className="card-action-item">
                              <button
                                className="card-action-btn"
                                aria-labelledby="card-label-3"
                              >
                                {/* <ion-icon name="eye-outline" /> */}
                              </button>
                              <div
                                className="card-action-tooltip"
                                id="card-label-3"
                              >
                                Quick View
                              </div>
                            </li>
                            <li className="card-action-item">
                              <button
                                className="card-action-btn"
                                aria-labelledby="card-label-4"
                              >
                                {/* <ion-icon name="repeat-outline" /> */}
                              </button>
                              <div
                                className="card-action-tooltip"
                                id="card-label-4"
                              >
                                Compare
                              </div>
                            </li>
                          </ul>
                        </figure>
                        <div className="card-content">
                          <div className="card-cat">
                            <a href="#" className="card-cat-link">
                              Men
                            </a>{" "}
                            /
                            <a href="#" className="card-cat-link">
                              Women
                            </a>
                          </div>
                          <h3 className="h3 card-title">
                            <a href="#">Simple Fabric Shoe</a>
                          </h3>
                          <data className="card-price" value="160.85">
                            $160.85
                          </data>
                        </div>
                      </div>
                    </li>
                    <li className="product-item">
                      <div className="product-card" tabIndex={0}>
                        <figure className="card-banner">
                          <Image
                            src="/assets/images/product-4.jpg"
                            width={312}
                            height={350}
                            loading="lazy"
                            alt="Air Jordan 7 Retro "
                            className="image-contain"
                          />
                          <div className="card-badge"> -25%</div>
                          <ul className="card-action-list">
                            <li className="card-action-item">
                              <button
                                className="card-action-btn"
                                aria-labelledby="card-label-1"
                              >
                                {/* <ion-icon name="cart-outline" /> */}
                              </button>
                              <div
                                className="card-action-tooltip"
                                id="card-label-1"
                              >
                                Add to Cart
                              </div>
                            </li>
                            <li className="card-action-item">
                              <button
                                className="card-action-btn"
                                aria-labelledby="card-label-2"
                              >
                                {/* <ion-icon name="heart-outline" /> */}
                              </button>
                              <div
                                className="card-action-tooltip"
                                id="card-label-2"
                              >
                                Add to Whishlist
                              </div>
                            </li>
                            <li className="card-action-item">
                              <button
                                className="card-action-btn"
                                aria-labelledby="card-label-3"
                              >
                                {/* <ion-icon name="eye-outline" /> */}
                              </button>
                              <div
                                className="card-action-tooltip"
                                id="card-label-3"
                              >
                                Quick View
                              </div>
                            </li>
                            <li className="card-action-item">
                              <button
                                className="card-action-btn"
                                aria-labelledby="card-label-4"
                              >
                                {/* <ion-icon name="repeat-outline" /> */}
                              </button>
                              <div
                                className="card-action-tooltip"
                                id="card-label-4"
                              >
                                Compare
                              </div>
                            </li>
                          </ul>
                        </figure>
                        <div className="card-content">
                          <div className="card-cat">
                            <a href="#" className="card-cat-link">
                              Men
                            </a>{" "}
                            /
                            <a href="#" className="card-cat-link">
                              Sports
                            </a>
                          </div>
                          <h3 className="h3 card-title">
                            <a href="#">Air Jordan 7 Retro </a>
                          </h3>
                          <data className="card-price" value="170.85">
                            $170.85 <del>$200.21</del>
                          </data>
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
            </section>

            <section className="section service">
              <div className="container">
                <ul className="service-list">
                  <li className="service-item">
                    <div className="service-card">
                      <div className="card-icon">
                        <Image
                          src="/assets/images/service-1.png"
                          width={53}
                          height={28}
                          loading="lazy"
                          alt="Service icon"
                        />
                      </div>
                      <div>
                        <h3 className="h4 card-title">Free Shiping</h3>
                        <p className="card-text">
                          All orders over <span>$150</span>
                        </p>
                      </div>
                    </div>
                  </li>
                  <li className="service-item">
                    <div className="service-card">
                      <div className="card-icon">
                        <Image
                          src="/assets/images/service-2.png"
                          width={43}
                          height={35}
                          loading="lazy"
                          alt="Service icon"
                        />
                      </div>
                      <div>
                        <h3 className="h4 card-title">Quick Payment</h3>
                        <p className="card-text">100% secure payment</p>
                      </div>
                    </div>
                  </li>
                  <li className="service-item">
                    <div className="service-card">
                      <div className="card-icon">
                        <Image
                          src="/assets/images/service-3.png"
                          width={40}
                          height={40}
                          loading="lazy"
                          alt="Service icon"
                        />
                      </div>
                      <div>
                        <h3 className="h4 card-title">Free Returns</h3>
                        <p className="card-text">Money back in 30 days</p>
                      </div>
                    </div>
                  </li>
                  <li className="service-item">
                    <div className="service-card">
                      <div className="card-icon">
                        <Image
                          src="/assets/images/service-4.png"
                          width={40}
                          height={40}
                          loading="lazy"
                          alt="Service icon"
                        />
                      </div>
                      <div>
                        <h3 className="h4 card-title">24/7 Support</h3>
                        <p className="card-text">Get Quick Support</p>
                      </div>
                    </div>
                  </li>
                </ul>
              </div>
            </section>

            <section className="section insta-post">
              <ul className="insta-post-list has-scrollbar">
                <li className="insta-post-item">
                  <Image
                    src="/assets/images/insta-1.jpg"
                    width={100}
                    height={100}
                    loading="lazy"
                    alt="Instagram post"
                    className="insta-post-banner image-contain"
                  />
                  <a href="#" className="insta-post-link">
                    {/* <ion-icon name="logo-instagram" /> */}
                  </a>
                </li>
                <li className="insta-post-item">
                  <Image
                    src="/assets/images/insta-2.jpg"
                    width={100}
                    height={100}
                    loading="lazy"
                    alt="Instagram post"
                    className="insta-post-banner image-contain"
                  />
                  <a href="#" className="insta-post-link">
                    {/* <ion-icon name="logo-instagram" /> */}
                  </a>
                </li>
                <li className="insta-post-item">
                  <Image
                    src="/assets/images/insta-3.jpg"
                    width={100}
                    height={100}
                    loading="lazy"
                    alt="Instagram post"
                    className="insta-post-banner image-contain"
                  />
                  <a href="#" className="insta-post-link">
                    {/* <ion-icon name="logo-instagram" /> */}
                  </a>
                </li>
                <li className="insta-post-item">
                  <Image
                    src="/assets/images/insta-4.jpg"
                    width={100}
                    height={100}
                    loading="lazy"
                    alt="Instagram post"
                    className="insta-post-banner image-contain"
                  />
                  <a href="#" className="insta-post-link">
                    {/* <ion-icon name="logo-instagram" /> */}
                  </a>
                </li>
                <li className="insta-post-item">
                  <Image
                    src="/assets/images/insta-5.jpg"
                    width={100}
                    height={100}
                    loading="lazy"
                    alt="Instagram post"
                    className="insta-post-banner image-contain"
                  />
                  <a href="#" className="insta-post-link">
                    {/* <ion-icon name="logo-instagram" /> */}
                  </a>
                </li>
                <li className="insta-post-item">
                  <Image
                    src="/assets/images/insta-6.jpg"
                    width={100}
                    height={100}
                    loading="lazy"
                    alt="Instagram post"
                    className="insta-post-banner image-contain"
                  />
                  <a href="#" className="insta-post-link">
                    {/* <ion-icon name="logo-instagram" /> */}
                  </a>
                </li>
                <li className="insta-post-item">
                  <Image
                    src="/assets/images/insta-7.jpg"
                    width={100}
                    height={100}
                    loading="lazy"
                    alt="Instagram post"
                    className="insta-post-banner image-contain"
                  />
                  <a href="#" className="insta-post-link">
                    {/* <ion-icon name="logo-instagram" /> */}
                  </a>
                </li>
                <li className="insta-post-item">
                  <Image
                    src="/assets/images/insta-8.jpg"
                    width={100}
                    height={100}
                    loading="lazy"
                    alt="Instagram post"
                    className="insta-post-banner image-contain"
                  />
                  <a href="#" className="insta-post-link">
                    {/* <ion-icon name="logo-instagram" /> */}
                  </a>
                </li>
              </ul>
            </section>
          </article>
        </main>

        <footer className="footer">
          <div className="footer-top section">
            <div className="container">
              <div className="footer-brand">
                <a href="#" className="logo">
                  <Image
                    src="/assets/images/logo.svg"
                    width={160}
                    height={50}
                    alt="Footcap logo"
                  />
                </a>
                <ul className="social-list">
                  <li>
                    <a href="#" className="social-link">
                      {/* <ion-icon name="logo-facebook" /> */}
                    </a>
                  </li>
                  <li>
                    <a href="#" className="social-link">
                      {/* <ion-icon name="logo-twitter" /> */}
                    </a>
                  </li>
                  <li>
                    <a href="#" className="social-link">
                      {/* <ion-icon name="logo-pinterest" /> */}
                    </a>
                  </li>
                  <li>
                    <a href="#" className="social-link">
                      {/* <ion-icon name="logo-linkedin" /> */}
                    </a>
                  </li>
                </ul>
              </div>
              <div className="footer-link-box">
                <ul className="footer-list">
                  <li>
                    <p className="footer-list-title">Contact Us</p>
                  </li>
                  <li>
                    <address className="footer-link">
                      {/* <ion-icon name="location" /> */}
                      <span className="footer-link-text">
                        2751 S Parker Rd, Aurora, CO 80014, United States
                      </span>
                    </address>
                  </li>
                  <li>
                    <a href="tel:+557343673257" className="footer-link">
                      {/* <ion-icon name="call" /> */}
                      <span className="footer-link-text">+557343673257</span>
                    </a>
                  </li>
                  <li>
                    <a href="mailto:footcap@help.com" className="footer-link">
                      {/* <ion-icon name="mail" /> */}
                      <span className="footer-link-text">footcap@help.com</span>
                    </a>
                  </li>
                </ul>
                <ul className="footer-list">
                  <li>
                    <p className="footer-list-title">My Account</p>
                  </li>
                  <li>
                    <a href="#" className="footer-link">
                      {/* <ion-icon name="chevron-forward-outline" /> */}
                      <span className="footer-link-text">My Account</span>
                    </a>
                  </li>
                  <li>
                    <a href="#" className="footer-link">
                      {/* <ion-icon name="chevron-forward-outline" /> */}
                      <span className="footer-link-text">View Cart</span>
                    </a>
                  </li>
                  <li>
                    <a href="#" className="footer-link">
                      {/* <ion-icon name="chevron-forward-outline" /> */}
                      <span className="footer-link-text">Wishlist</span>
                    </a>
                  </li>
                  <li>
                    <a href="#" className="footer-link">
                      {/* <ion-icon name="chevron-forward-outline" /> */}
                      <span className="footer-link-text">Compare</span>
                    </a>
                  </li>
                  <li>
                    <a href="#" className="footer-link">
                      {/* <ion-icon name="chevron-forward-outline" /> */}
                      <span className="footer-link-text">New Products</span>
                    </a>
                  </li>
                </ul>
                <div className="footer-list">
                  <p className="footer-list-title">Opening Time</p>
                  <table className="footer-table">
                    <tbody>
                      <tr className="table-row">
                        <th className="table-head" scope="row">
                          Mon - Tue:
                        </th>
                        <td className="table-data">8AM - 10PM</td>
                      </tr>
                      <tr className="table-row">
                        <th className="table-head" scope="row">
                          Wed:
                        </th>
                        <td className="table-data">8AM - 7PM</td>
                      </tr>
                      <tr className="table-row">
                        <th className="table-head" scope="row">
                          Fri:
                        </th>
                        <td className="table-data">7AM - 12PM</td>
                      </tr>
                      <tr className="table-row">
                        <th className="table-head" scope="row">
                          Sat:
                        </th>
                        <td className="table-data">9AM - 8PM</td>
                      </tr>
                      <tr className="table-row">
                        <th className="table-head" scope="row">
                          Sun:
                        </th>
                        <td className="table-data">Closed</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div className="footer-list">
                  <p className="footer-list-title">Newsletter</p>
                  <p className="newsletter-text">
                    Authoritatively morph 24/7 potentialities with error-free
                    partnerships.
                  </p>
                  <form action="" className="newsletter-form">
                    <input
                      type="email"
                      name="email"
                      placeholder="Email Address"
                      className="newsletter-input"
                    />
                    <button type="submit" className="btn btn-primary">
                      Subscribe
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
          <div className="footer-bottom">
            <div className="container">
              <p className="copyright">
                © 2022{" "}
                <a href="#" className="copyright-link">
                  codewithsadee
                </a>
                . All Rights Reserved
              </p>
            </div>
          </div>
        </footer>

        <a href="#top" className="go-top-btn" data-go-top="">
          {/* <ion-icon name="arrow-up-outline" /> */}
        </a>
      </>
    </div>
  );
};

export default Home;
